import { User, Exchange, Review, Notification, LeaderboardEntry } from "@/types";

export const MOCK_USERS: User[] = [
  {
    _id: "1",
    name: "Youssef Benali",
    email: "youssef@example.com",
    username: "youssef.benali",
    image: "https://randomuser.me/api/portraits/men/1.jpg",
    bio: "Full-stack developer passionate about open source. I can teach you React, Node.js, and MongoDB. Looking to learn Arabic calligraphy and music production.",
    city: "Casablanca",
    country: "Morocco",
    skillsTeach: [
      { name: "React.js", category: "technology", level: "expert", description: "Modern React with hooks, context, and TypeScript" },
      { name: "Node.js", category: "technology", level: "advanced", description: "REST APIs, authentication, databases" },
      { name: "MongoDB", category: "technology", level: "advanced" },
    ],
    skillsLearn: [
      { name: "Arabic Calligraphy", category: "art", level: "beginner" },
      { name: "Music Production", category: "music", level: "beginner" },
    ],
    level: 7,
    xp: 2450,
    badges: [
      { id: "first_exchange", name: "First Exchange", description: "Completed your first skill swap", icon: "🤝", earnedAt: new Date("2024-01-15") },
      { id: "top_teacher", name: "Top Teacher", description: "Received 10 five-star reviews", icon: "⭐", earnedAt: new Date("2024-03-20") },
      { id: "streak_30", name: "30-Day Streak", description: "Active for 30 consecutive days", icon: "🔥", earnedAt: new Date("2024-04-01") },
    ],
    rating: 4.9,
    reviewCount: 24,
    isVerified: true,
    isOnline: true,
    lastSeen: new Date(),
    socialLinks: { github: "https://github.com/youssef", linkedin: "https://linkedin.com/in/youssef" },
    joinedAt: new Date("2023-11-01"),
    completedExchanges: 18,
    languages: ["Arabic", "French", "English"],
  },
  {
    _id: "2",
    name: "Fatima Zahra",
    email: "fatima@example.com",
    username: "fatima.zahra",
    image: "https://randomuser.me/api/portraits/women/2.jpg",
    bio: "UX/UI designer with 4 years of experience in Figma and user research. Want to learn programming to build my own products.",
    city: "Rabat",
    country: "Morocco",
    skillsTeach: [
      { name: "UI/UX Design", category: "design", level: "expert" },
      { name: "Figma", category: "design", level: "expert" },
      { name: "User Research", category: "design", level: "advanced" },
    ],
    skillsLearn: [
      { name: "Python", category: "technology", level: "beginner" },
      { name: "JavaScript", category: "technology", level: "beginner" },
    ],
    level: 6,
    xp: 1800,
    badges: [
      { id: "first_exchange", name: "First Exchange", description: "Completed your first skill swap", icon: "🤝", earnedAt: new Date("2024-01-20") },
      { id: "design_master", name: "Design Master", description: "Taught design to 5+ people", icon: "🎨", earnedAt: new Date("2024-02-15") },
    ],
    rating: 4.8,
    reviewCount: 16,
    isVerified: true,
    isOnline: false,
    lastSeen: new Date(Date.now() - 3600000),
    socialLinks: { linkedin: "https://linkedin.com/in/fatima" },
    joinedAt: new Date("2023-12-01"),
    completedExchanges: 12,
    languages: ["Arabic", "French", "English"],
  },
  {
    _id: "3",
    name: "Karim El Mansouri",
    email: "karim@example.com",
    username: "karim.elmansouri",
    image: "https://randomuser.me/api/portraits/men/3.jpg",
    bio: "Digital marketing expert and content creator. 5 years growing brands online. Want to learn data science to level up my analytics game.",
    city: "Marrakech",
    country: "Morocco",
    skillsTeach: [
      { name: "Digital Marketing", category: "business", level: "expert" },
      { name: "Content Creation", category: "writing", level: "advanced" },
      { name: "SEO", category: "business", level: "advanced" },
    ],
    skillsLearn: [
      { name: "Data Science", category: "technology", level: "beginner" },
      { name: "Python", category: "technology", level: "intermediate" },
    ],
    level: 5,
    xp: 1200,
    badges: [
      { id: "first_exchange", name: "First Exchange", description: "Completed your first skill swap", icon: "🤝", earnedAt: new Date("2024-02-01") },
    ],
    rating: 4.7,
    reviewCount: 9,
    isVerified: false,
    isOnline: true,
    lastSeen: new Date(),
    socialLinks: { twitter: "https://twitter.com/karim" },
    joinedAt: new Date("2024-01-15"),
    completedExchanges: 7,
    languages: ["Arabic", "French"],
  },
  {
    _id: "4",
    name: "Nadia Chraibi",
    email: "nadia@example.com",
    username: "nadia.chraibi",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
    bio: "Music producer and guitarist. Gigged across Morocco and Spain. Teaching guitar, piano, and music theory in exchange for web dev skills.",
    city: "Casablanca",
    country: "Morocco",
    skillsTeach: [
      { name: "Guitar", category: "music", level: "expert" },
      { name: "Music Theory", category: "music", level: "advanced" },
      { name: "Music Production", category: "music", level: "advanced" },
    ],
    skillsLearn: [
      { name: "Web Development", category: "technology", level: "beginner" },
      { name: "Graphic Design", category: "design", level: "beginner" },
    ],
    level: 8,
    xp: 3200,
    badges: [
      { id: "music_master", name: "Music Master", description: "Completed 20 music lessons", icon: "🎵", earnedAt: new Date("2024-01-01") },
      { id: "top_teacher", name: "Top Teacher", description: "10 five-star reviews", icon: "⭐", earnedAt: new Date("2024-02-10") },
      { id: "verified", name: "Verified Pro", description: "Identity verified", icon: "✅", earnedAt: new Date("2023-12-01") },
    ],
    rating: 5.0,
    reviewCount: 31,
    isVerified: true,
    isOnline: false,
    lastSeen: new Date(Date.now() - 7200000),
    socialLinks: { website: "https://nadia-music.ma" },
    joinedAt: new Date("2023-10-01"),
    completedExchanges: 28,
    languages: ["Arabic", "French", "Spanish", "English"],
  },
  {
    _id: "5",
    name: "Hamza Tazi",
    email: "hamza@example.com",
    username: "hamza.tazi",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
    bio: "Chef and culinary instructor at a Fès restaurant. Master of Moroccan cuisine and pastry. Want to learn English and digital photography.",
    city: "Fès",
    country: "Morocco",
    skillsTeach: [
      { name: "Moroccan Cuisine", category: "cooking", level: "expert" },
      { name: "Pastry & Baking", category: "cooking", level: "advanced" },
      { name: "Nutrition Planning", category: "fitness", level: "intermediate" },
    ],
    skillsLearn: [
      { name: "English", category: "language", level: "intermediate" },
      { name: "Photography", category: "art", level: "beginner" },
    ],
    level: 4,
    xp: 750,
    badges: [
      { id: "first_exchange", name: "First Exchange", description: "Completed your first skill swap", icon: "🤝", earnedAt: new Date("2024-03-01") },
      { id: "culinary_pro", name: "Culinary Pro", description: "Taught cooking to 10 people", icon: "🍳", earnedAt: new Date("2024-04-15") },
    ],
    rating: 4.9,
    reviewCount: 11,
    isVerified: true,
    isOnline: true,
    lastSeen: new Date(),
    socialLinks: {},
    joinedAt: new Date("2024-02-01"),
    completedExchanges:9,
    languages: ["Arabic", "French"],
  },
  {
    _id: "6",
    name: "Leila Moussaoui",
    email: "leila@example.com",
    username: "leila.moussaoui",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
    bio: "Personal trainer and yoga instructor. 6 years helping people transform their bodies and minds. Looking to learn business and marketing.",
    city: "Agadir",
    country: "Morocco",
    skillsTeach: [
      { name: "Personal Training", category: "fitness", level: "expert" },
      { name: "Yoga", category: "fitness", level: "expert" },
      { name: "Nutrition", category: "fitness", level: "advanced" },
    ],
    skillsLearn: [
      { name: "Business Strategy", category: "business", level: "beginner" },
      { name: "Social Media Marketing", category: "business", level: "beginner" },
    ],
    level: 6,
    xp: 1650,
    badges: [
      { id: "fitness_guru", name: "Fitness Guru", description: "Completed 15 fitness exchanges", icon: "💪", earnedAt: new Date("2024-01-10") },
      { id: "top_teacher", name: "Top Teacher", description: "10 five-star reviews", icon: "⭐", earnedAt: new Date("2024-03-05") },
    ],
    rating: 4.8,
    reviewCount: 19,
    isVerified: true,
    isOnline: false,
    lastSeen: new Date(Date.now() - 1800000),
    socialLinks: { twitter: "https://twitter.com/leila_fit" },
    joinedAt: new Date("2023-11-15"),
    completedExchanges: 15,
    languages: ["Arabic", "French", "English"],
  },
];

export const MOCK_EXCHANGES: Exchange[] = [
  {
    _id: "ex1",
    requester: MOCK_USERS[0],
    receiver: MOCK_USERS[1],
    requesterSkill: { name: "React.js", category: "technology", level: "expert" },
    receiverSkill: { name: "UI/UX Design", category: "design", level: "expert" },
    status: "active",
    message: "Hey! I love your design work. I can teach you React in exchange for UI/UX design sessions.",
    sessions: [
      { _id: "s1", exchangeId: "ex1", date: new Date(Date.now() + 86400000), duration: 60, meetLink: "https://meet.google.com/abc-def-ghi", status: "scheduled" },
    ],
    createdAt: new Date(Date.now() - 7 * 86400000),
    updatedAt: new Date(),
  },
  {
    _id: "ex2",
    requester: MOCK_USERS[2],
    receiver: MOCK_USERS[0],
    requesterSkill: { name: "Digital Marketing", category: "business", level: "expert" },
    receiverSkill: { name: "Node.js", category: "technology", level: "advanced" },
    status: "pending",
    message: "I can grow your online presence, teach me backend development?",
    sessions: [],
    createdAt: new Date(Date.now() - 2 * 86400000),
    updatedAt: new Date(),
  },
  {
    _id: "ex3",
    requester: MOCK_USERS[0],
    receiver: MOCK_USERS[3],
    requesterSkill: { name: "MongoDB", category: "technology", level: "advanced" },
    receiverSkill: { name: "Guitar", category: "music", level: "expert" },
    status: "completed",
    message: "Would love to learn guitar. I can teach you database design.",
    sessions: [
      { _id: "s2", exchangeId: "ex3", date: new Date(Date.now() - 14 * 86400000), duration: 90, meetLink: "https://zoom.us/j/123456", status: "completed" },
      { _id: "s3", exchangeId: "ex3", date: new Date(Date.now() - 7 * 86400000), duration: 90, status: "completed" },
    ],
    createdAt: new Date(Date.now() - 30 * 86400000),
    updatedAt: new Date(),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    _id: "r1",
    reviewer: MOCK_USERS[1],
    reviewee: MOCK_USERS[0],
    exchangeId: "ex3",
    rating: 5,
    comment: "Youssef is an incredible teacher! His React lessons were clear, structured, and super practical. Highly recommend!",
    skillTaught: "React.js",
    createdAt: new Date(Date.now() - 5 * 86400000),
  },
  {
    _id: "r2",
    reviewer: MOCK_USERS[3],
    reviewee: MOCK_USERS[0],
    exchangeId: "ex3",
    rating: 5,
    comment: "Learned so much about MongoDB from Youssef. Very patient and knowledgeable. 10/10 would swap again!",
    skillTaught: "MongoDB",
    createdAt: new Date(Date.now() - 6 * 86400000),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    _id: "n1",
    userId: "1",
    type: "exchange_request",
    title: "New Exchange Request",
    message: "Karim wants to swap Digital Marketing for Node.js",
    link: "/dashboard",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 86400000),
    fromUser: { _id: "3", name: "Karim El Mansouri", image: MOCK_USERS[2].image, username: "karim.elmansouri" },
  },
  {
    _id: "n2",
    userId: "1",
    type: "new_review",
    title: "New Review",
    message: "Fatima gave you a 5-star review!",
    link: "/profile/youssef.benali",
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 86400000),
    fromUser: { _id: "2", name: "Fatima Zahra", image: MOCK_USERS[1].image, username: "fatima.zahra" },
  },
  {
    _id: "n3",
    userId: "1",
    type: "session_reminder",
    title: "Session Tomorrow",
    message: "Your React/Design session with Fatima is tomorrow at 10:00",
    link: "/dashboard",
    isRead: true,
    createdAt: new Date(Date.now() - 86400000),
  },
  {
    _id: "n4",
    userId: "1",
    type: "badge_earned",
    title: "Badge Earned!",
    message: "You earned the 'Top Teacher' badge",
    isRead: true,
    createdAt: new Date(Date.now() - 10 * 86400000),
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = MOCK_USERS
  .sort((a, b) => b.xp - a.xp)
  .map((user, index) => ({
    rank: index + 1,
    user,
    xp: user.xp,
    exchanges: user.completedExchanges,
  }));

export const TRENDING_SKILLS = [
  { name: "React.js", category: "technology", count: 142, trending: true },
  { name: "UI/UX Design", category: "design", count: 98, trending: true },
  { name: "Python", category: "technology", count: 87, trending: false },
  { name: "Digital Marketing", category: "business", count: 76, trending: true },
  { name: "Figma", category: "design", count: 65, trending: false },
  { name: "Moroccan Darija", category: "language", count: 54, trending: true },
  { name: "Guitar", category: "music", count: 48, trending: false },
  { name: "Yoga", category: "fitness", count: 43, trending: true },
  { name: "Video Editing", category: "design", count: 38, trending: false },
  { name: "Public Speaking", category: "business", count: 34, trending: true },
];
